name: build

on:
  push:
    branches: [ 'master', 'rsgx1.1.2' ]
  pull_request:
    branches: [ 'master', 'rsgx1.1.2' ]

jobs:
  test:

    runs-on: ubuntu-18.04
    container: 
      image: baiduxlab/sgx-rust:1804-1.1.2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Github Actions' $HOME
      run: |
        cp /root/.bashrc $HOME/.bashrc &&
        ln -sf /root/.rustup ~/.rustup &&
        ln -sf /root/.cargo ~/.cargo
    - name: Rust toolchains
      run: |
        . ~/.cargo/env && 
        rustc --version &&
        rustup --version &&
        cargo --version
      shell: bash
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Run tests
      run: |
        . ~/.cargo/env && 
        . /opt/sgxsdk/environment && 
        mkdir tests/sgx/build &&
        cd tests/sgx/build &&
        cmake .. && 
        make &&
        make test-sgx
      shell: bash
